-- Corrige la tabla payroll_bonus: agrega columna date si no existe
-- También recrea la tabla limpiamente si es necesario

-- Si la tabla existe pero le falta la columna date, agréguala:
ALTER TABLE IF EXISTS public.payroll_bonus 
  ADD COLUMN IF NOT EXISTS date date;

-- Recrea la tabla limpiamente desde cero (solo si hay errores persistentes):
-- DROP TABLE IF EXISTS public.payroll_bonus;

CREATE TABLE IF NOT EXISTS public.payroll_bonus (
    id bigint generated by default as identity primary key,
    employee_id integer references public.empleados(id_empleado) on delete cascade not null,
    amount numeric(10,2) not null,
    reason text,
    type text default 'performance',
    date date not null,
    created_at timestamp with time zone default now()
);

-- RLS
ALTER TABLE public.payroll_bonus ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable all operations for users" ON public.payroll_bonus;
CREATE POLICY "Enable all operations for users" ON public.payroll_bonus FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Enable all operations for admin" ON public.payroll_bonus;
CREATE POLICY "Enable all operations for admin" ON public.payroll_bonus FOR ALL TO service_role USING (true) WITH CHECK (true);
