-- ==========================================
-- 1. FIX: TABLA PARA CONFIGURACIÓN DE EMPRESA
-- ==========================================
CREATE TABLE IF NOT EXISTS public.configuracion_empresa (
    id bigint generated by default as identity primary key,
    nombre_empresa text not null default 'Mi Empresa',
    direccion text,
    rfc text,
    registro_patronal text,
    logo_base64 text,
    created_at timestamp with time zone default now()
);

ALTER TABLE public.configuracion_empresa ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "all_auth_emp" ON public.configuracion_empresa;
CREATE POLICY "all_auth_emp" ON public.configuracion_empresa FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- ==========================================
-- 2. FIX: COLUMNA FALTANTE EN PAYROLL BONUS
-- ==========================================

-- Intentamos agregar la columna date si no existe
ALTER TABLE public.payroll_bonus ADD COLUMN IF NOT EXISTS date date;

-- Nos aseguramos que la tabla exista por completo (si el ALTER de arriba falla, esto la crea)
CREATE TABLE IF NOT EXISTS public.payroll_bonus (
    id bigint generated by default as identity primary key,
    employee_id integer references public.empleados(id_empleado) on delete cascade not null,
    amount numeric(10,2) not null,
    reason text,
    type text default 'performance',
    date date not null,
    created_at timestamp with time zone default now()
);

ALTER TABLE public.payroll_bonus ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "all_auth_bonus" ON public.payroll_bonus;
CREATE POLICY "all_auth_bonus" ON public.payroll_bonus FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- ==========================================
-- 3. FIX: RECARGAR EL CACHÉ DEL SCHEMA (CLAVE)
-- ==========================================
NOTIFY pgrst, 'reload schema';
