-- ========================================================
-- SCRIPT DE MANTENIMIENTO INTEGRAL - WORKTRACK PRO
-- ========================================================

-- 1. ASEGURAR TABLA Y COLUMNAS DE CONFIGURACIÓN DE EMPRESA
CREATE TABLE IF NOT EXISTS public.configuracion_empresa (
    id bigint generated by default as identity primary key,
    nombre_empresa text not null default 'Mi Empresa',
    direccion text,
    rfc text,
    registro_patronal text,
    logo_base64 text,
    created_at timestamp with time zone default now()
);

-- Agregar columnas faltantes una por una (evita errores si ya existen)
ALTER TABLE public.configuracion_empresa ADD COLUMN IF NOT EXISTS actualizado_el timestamp with time zone default now();
ALTER TABLE public.configuracion_empresa ADD COLUMN IF NOT EXISTS nombre_empresa text default 'Mi Empresa';
ALTER TABLE public.configuracion_empresa ADD COLUMN IF NOT EXISTS logo_base64 text;

-- 2. ASEGURAR TABLA Y COLUMNAS DE BONOS DE NÓMINA
CREATE TABLE IF NOT EXISTS public.payroll_bonus (
    id bigint generated by default as identity primary key,
    employee_id integer references public.empleados(id_empleado) on delete cascade not null,
    amount numeric(10,2) not null,
    reason text,
    type text default 'performance',
    date date not null,
    created_at timestamp with time zone default now()
);

-- Agregar columnas faltantes una por una
ALTER TABLE public.payroll_bonus ADD COLUMN IF NOT EXISTS type text default 'performance';
ALTER TABLE public.payroll_bonus ADD COLUMN IF NOT EXISTS date date;
ALTER TABLE public.payroll_bonus ADD COLUMN IF NOT EXISTS reason text;

-- 3. PERMISOS Y SEGURIDAD (RLS)
ALTER TABLE public.configuracion_empresa ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payroll_bonus ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "all_auth_config" ON public.configuracion_empresa;
CREATE POLICY "all_auth_config" ON public.configuracion_empresa FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "all_auth_bonus" ON public.payroll_bonus;
CREATE POLICY "all_auth_bonus" ON public.payroll_bonus FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- 4. FORZAR RECARGA DEL CACHÉ DE LA API (CRÍTICO)
-- Esto limpia el error "Could not find column in schema cache"
NOTIFY pgrst, 'reload schema';
